[Hotkeys]
; =====================
; Primary Towers
; =====================
dart             = q
boomer        = w
bomb             = e
tack             = r
ice              = t
glue             = y
desperado        = o

; =====================
; Military Towers
; =====================
sniper     = z
sub        = x
boat        = c
ace        = v
heli       = b
mortar     = n
dartling   = m

; =====================
; Magic Towers
; =====================
wizard           = a
super            = s
ninja            = d
alch       = f
druid            = g
mermonkey        = p

; =====================
; Support Towers                   
; =====================
farm      = h 
spike            = j
village          = k
engineer         = l
beast            = i


; =====================
; Hero
; =====================
hero            = u




; =====================
; Map Data
; =====================
[Map]
tricky_tracks   = 1,1
glacial_trail   = 1,2
dark_dungeons   = 1,3
sanctuary       = 1,4
ravine          = 1,5
flooded_valley  = 1,6
infernal        = 2,1
bloody_puddles  = 2,2
workshop        = 2,3
quad            = 2,4
dark_castle     = 2,5
muddy_puddles   = 2,6
ouch            = 3,1