[Hotkeys]
; =====================
; Primary Towers
; =====================
dart             = q
boomer        = w
bomb             = e
tack             = r
ice              = t
glue             = y
desperado        = o

; =====================
; Military Towers
; =====================
sniper     = z
sub        = x
boat        = c
ace        = v
heli       = b
mortar     = n
dartling   = m

; =====================
; Magic Towers
; =====================
wizard           = a
super            = s
ninja            = d
alch       = f
druid            = g
mermonkey        = p

; =====================
; Support Towers                   
; =====================
farm      = h 
spike            = j
village          = k
engineer         = l
beast            = i


; =====================
; Hero
; =====================
hero            = u




; =====================
; Map Data
; =====================
[Map]
glacial_trail   = 1,1
dark_dungeons   = 1,2
sanctuary       = 1,3
ravine          = 1,4
flooded_valley  = 1,5
infernal        = 1,6
bloody_puddles  = 2,1
workshop        = 2,2
quad            = 2,3
dark_castle     = 2,4
muddy_puddles   = 2,5
ouch            = 2,6